#!/usr/bin/sh

if [ $# -ne 7 ]
then
    echo "Usage: `basename $0` problems base-dir report out-dir max-time max-mem e-time"
    exit 65
fi

# Input.
PROBLEMS="$1"
BASE_DIR="$2"
# Output.
REPORT="$3"
OUT_DIR="$4"
# Settings.
MAX_TIME="$5"
MAX_MEM="$6"
E_TIME="$7"

mkdir -p "$OUT_DIR"

OUT="$OUT_DIR/mace4"
mkdir -p "$OUT"
./run_mace4.opt "$REPORT" "Mace" "$PROBLEMS" "$OUT" \
  --base-dir="$BASE_DIR" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=-b --opt=-1

OUT="$OUT_DIR/paradox"
mkdir -p "$OUT"
./run_paradox.opt "$REPORT" "Paradox" "$PROBLEMS" "$OUT" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--root --opt="$BASE_DIR"

OUT="$OUT_DIR/iprover"
mkdir -p "$OUT"
./run_iprover.opt "$REPORT" "iProver" "$PROBLEMS" "$OUT" \
  --exe="./iproveropt" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--include_path --opt="$BASE_DIR" \
  --opt=--schedule --opt=sat

OUT="$OUT_DIR/iprover-fin"
mkdir -p "$OUT"
./run_iprover.opt "$REPORT" "iProver/Fin" "$PROBLEMS" "$OUT" \
  --exe="./iproveropt" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--include_path --opt="$BASE_DIR" \
  --opt=--sat_mode --opt=true \
  --opt=--schedule --opt=none \
  --opt=--sat_finite_models --opt=true

for solver in "cryptominisat" "minisat" "josat" "gecode"
do
  case $solver in
    cryptominisat) cfg="CMSat";;
    minisat) cfg="MiniSat";;
    josat) cfg="Josat";;
    gecode) cfg="Gecode";;
  esac

  OUT="$OUT_DIR/$solver"
  mkdir -p "$OUT"
  ./run_crossbow.opt "$REPORT" "$cfg" "$PROBLEMS" "$OUT" \
    --exe=./crossbow.opt \
    --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
    --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=$solver

  OUT="$OUT_DIR/$solver-e"
  mkdir -p "$OUT"
  ./run_crossbow.opt "$REPORT" "$cfg+E" "$PROBLEMS" "$OUT" \
    --exe=./crossbow.opt \
    --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
    --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=$solver \
    --opt=--use-e --opt=--e-max-secs --opt="$E_TIME"
done

OUT="$OUT_DIR/gecode-flat"
mkdir -p "$OUT"
./run_crossbow.opt "$REPORT" "FGecode" "$PROBLEMS" "$OUT" \
  --exe=./crossbow.opt \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=gecode \
  --opt=--detect-commutativity --opt=--detect-hints-for-groups \
  --opt=--detect-hints-for-quasigroups \
  --opt=--detect-hints-for-involutive-funcs \
  --opt=--rewrite-ground-terms --opt=--unflatten \
  --opt=--define-ground-terms --opt=--flatten \
  --opt=--paradox-mod-splitting

OUT="$OUT_DIR/gecode-flat-e"
mkdir -p "$OUT"
./run_crossbow.opt "$REPORT" "FGecode+E" "$PROBLEMS" "$OUT" \
  --exe=./crossbow.opt \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=gecode \
  --opt=--detect-commutativity --opt=--detect-hints-for-groups \
  --opt=--detect-hints-for-quasigroups \
  --opt=--detect-hints-for-involutive-funcs \
  --opt=--rewrite-ground-terms --opt=--unflatten \
  --opt=--define-ground-terms --opt=--flatten \
  --opt=--paradox-mod-splitting \
  --opt=--use-e --opt=--e-max-secs --opt="$E_TIME"
