#!/usr/bin/sh

if [ $# -ne 6 ]
then
    echo "Usage: `basename $0` problems base-dir out-dir max-time max-mem e-time"
    exit 65
fi

# Input.
PROBLEMS="$1"
BASE_DIR="$2"
# Output.
OUT_DIR="$3"
# Settings.
MAX_TIME="$4"
MAX_MEM="$5"
E_TIME="$6"

mkdir -p "$OUT_DIR"

OUT="$OUT_DIR/mace4"
mkdir "$OUT"
./run_mace4.opt "Mace" "$PROBLEMS" "$OUT" \
  --base-dir="$BASE_DIR" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=-b --opt=-1

OUT="$OUT_DIR/paradox"
mkdir "$OUT"
./run_paradox.opt "Paradox" "$PROBLEMS" "$OUT" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--root --opt="$BASE_DIR"

OUT="$OUT_DIR/iprover"
mkdir "$OUT"
./run_iprover.opt "iProver" "$PROBLEMS" "$OUT" \
  --exe="./iproveropt" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--include_path --opt="$BASE_DIR" \
  --opt=--schedule --opt=sat

OUT="$OUT_DIR/iprover-fin"
mkdir "$OUT"
./run_iprover.opt "iProver/Fin" "$PROBLEMS" "$OUT" \
  --exe="./iproveropt" \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--include_path --opt="$BASE_DIR" \
  --opt=--sat_mode --opt=true \
  --opt=--schedule --opt=none \
  --opt=--sat_finite_models --opt=true

for solver in "cryptominisat" "minisat" "josat" "gecode"
do
  case $solver in
    cryptominisat) cfg="CMSat";;
    minisat) cfg="MiniSat";;
    josat) cfg="Josat";;
    gecode) cfg="Gecode";;
  esac

  OUT="$OUT_DIR/$solver"
  mkdir "$OUT"
  ./run_crossbow.opt "$cfg" "$PROBLEMS" "$OUT" \
    --exe=./crossbow.opt \
    --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
    --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=$solver

  OUT="$OUT_DIR/$solver-e"
  mkdir "$OUT"
  ./run_crossbow.opt "$cfg+E" "$PROBLEMS" "$OUT" \
    --exe=./crossbow.opt \
    --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
    --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=$solver \
    --opt=--use-e --opt=--e-max-secs --opt="$E_TIME"
done

OUT="$OUT_DIR/gecode-flat"
mkdir "$OUT"
./run_crossbow.opt "FGecode" "$PROBLEMS" "$OUT" \
  --exe=./crossbow.opt \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=gecode \
  --opt=--detect-commutativity --opt=--detect-hints-for-groups \
  --opt=--detect-hints-for-quasigroups \
  --opt=--detect-hints-for-involutive-funcs \
  --opt=--rewrite-ground-terms --opt=--unflatten \
  --opt=--define-ground-terms --opt=--flatten \
  --opt=--paradox-mod-splitting

OUT="$OUT_DIR/gecode-flat-e"
mkdir "$OUT"
./run_crossbow.opt "FGecode+E" "$PROBLEMS" "$OUT" \
  --exe=./crossbow.opt \
  --max-time="$MAX_TIME" --max-mem="$MAX_MEM" \
  --opt=--base-dir --opt="$BASE_DIR" --opt=--solver=gecode \
  --opt=--detect-commutativity --opt=--detect-hints-for-groups \
  --opt=--detect-hints-for-quasigroups \
  --opt=--detect-hints-for-involutive-funcs \
  --opt=--rewrite-ground-terms --opt=--unflatten \
  --opt=--define-ground-terms --opt=--flatten \
  --opt=--paradox-mod-splitting \
  --opt=--use-e --opt=--e-max-secs --opt="$E_TIME"

./results_to_latex.opt "$OUT_DIR/results.tex" \
  "$OUT_DIR/mace4" "$OUT_DIR/paradox" \
  "$OUT_DIR/iprover" "$OUT_DIR/iprover-fin" \
  "$OUT_DIR/cryptominisat" "$OUT_DIR/cryptominisat-e" \
  "$OUT_DIR/minisat" "$OUT_DIR/minisat-e" \
  "$OUT_DIR/josat" "$OUT_DIR/josat-e" \
  "$OUT_DIR/gecode" "$OUT_DIR/gecode-e" \
  "$OUT_DIR/gecode-flat" "$OUT_DIR/gecode-flat-e"
