#!/usr/bin/sh

if [ $# -lt 3 ]
then
    echo "Usage: `basename $0` summary reduced groups"
    exit 65
fi

SUMMARY="$1"
REDUCED="$2"

shift
shift

CMD="./summary_to_latex.opt $SUMMARY $# $@"

PROVERS_FULL="\
    mace4 paradox \
    iprover iprover-fin \
    cryptominisat cryptominisat-e \
    minisat minisat-e \
    josat josat-e \
    gecode gecode-e \
    gecode-flat gecode-flat-e"

PROVERS_REDUCED="\
    mace4 \
    paradox \
    iprover-fin \
    minisat-e \
    gecode-e"

PROVERS="$PROVERS_FULL"

if [ "$REDUCED" -eq "1" ]
then
    PROVERS="$PROVERS_REDUCED"
fi

for prover in $PROVERS
do
    DIR="$prover"

    for group in "$@"
    do
        CMD="$CMD $group/$DIR"
    done
done

eval "$CMD"
